#!/bin/bash
# Shell script to run the Jekyll site locally (and remind you where to preview it)
#         --->   Note: You must have Ruby and Jekyll installed locally to run this
bundle exec jekyll serve
